setup github actions workflows for feature and main branch & jacoco

diff --git a/.github/workflows/feature-branch.yaml b/.github/workflows/feature-branch.yaml
--- a/.github/workflows/feature-branch.yaml
+++ b/.github/workflows/feature-branch.yaml
@@ -16,9 +16,6 @@ permissions:
 jobs:
   build_branch:
     runs-on: ubuntu-latest
-    env:
-      REPOSITORY_NAME: "digiboard"
-      IMAGE_TAG: "latest"
 
     steps:
       # A- Set up runner
@@ -30,20 +27,19 @@ jobs:
         with:
           java-version: "21"
           distribution: "temurin"
-          cache: maven
-
-      - name: Get node_modules cache
-        uses: actions/cache@v3.0.2
-        id: node_modules_cache
+      - name: Get maven repository cache
+        uses: actions/cache@v4
+        id: maven_local_repo_cache
         with:
-          path: "**/node_modules **/next/cache"
-          key: ${{ runner.os }}-node_modules_cache-${{ hashFiles('**/package-lock.json') }}
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
-            ${{ runner.os }}-node_modules_cache-
+            ${{ runner.os }}-maven-
 
       # B- build artifact
       - name: build artifact
-        run: mvn -B package
+        run: mvn clean package
+
       # C- Generate and publish test report for java artifact
       - name: Publish java test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
@@ -57,7 +53,7 @@ jobs:
         id: jacoco_reporter
         uses: PavanMudigonda/jacoco-reporter@v4.8
         with:
-          coverage_results_path: ./arthur-digiboard-backend/target/site/jacoco/jacoco.xml
+          coverage_results_path: ./target/site/jacoco/jacoco.xml
           coverage_report_name: Coverage
           coverage_report_title: JaCoCo
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -91,29 +87,29 @@ jobs:
           name: Spotbugs
           path: build/reports/spotbugs/*.xml
 
-      # D- build and scan docker image
-      - name: Build and tag docker temp
-        run: |
-          docker build -t ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}} .
+      # # D- build and scan docker image
+      # - name: Build and tag docker temp
+      #   run: |
+      #     docker build -t ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}} .
 
-      ## scan docker image for vulnerabilities
-      - name: Run Snyk to check Docker image for vulnerabilities
-        id: snyk_scan
-        continue-on-error: true
-        uses: snyk/actions/docker@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          image: ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}}
-          args: --file=Dockerfile --severity-threshold=high
+      # ## scan docker image for vulnerabilities
+      # - name: Run Snyk to check Docker image for vulnerabilities
+      #   id: snyk_scan
+      #   continue-on-error: true
+      #   uses: snyk/actions/docker@master
+      #   env:
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #   with:
+      #     image: ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}}
+      #     args: --file=Dockerfile --severity-threshold=high
 
-      - name: Upload result to GitHub Code Scanning
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: snyk.sarif
+      # - name: Upload result to GitHub Code Scanning
+      #   uses: github/codeql-action/upload-sarif@v2
+      #   with:
+      #     sarif_file: snyk.sarif
 
-      - name: Snyk Scan Result Check
-        if: ${{ steps.snyk_scan.outcome == 'failure' }}
-        run: |
-          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
-          exit 1
+      # - name: Snyk Scan Result Check
+      #   if: ${{ steps.snyk_scan.outcome == 'failure' }}
+      #   run: |
+      #     echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+      #     exit 1
diff --git a/.github/workflows/main-branch.yaml b/.github/workflows/main-branch.yaml
--- a/.github/workflows/main-branch.yaml
+++ b/.github/workflows/main-branch.yaml
@@ -17,9 +17,6 @@ permissions:
 jobs:
   build_branch:
     runs-on: ubuntu-latest
-    env:
-      REPOSITORY_NAME: "digiboard"
-      IMAGE_TAG: "latest"
 
     steps:
       # A- Set up runner
@@ -31,26 +28,18 @@ jobs:
         with:
           java-version: "21"
           distribution: "temurin"
-      - name: Get node_modules cache
-        uses: actions/cache@v3.0.2
-        id: node_modules_cache
+      - name: Get maven repository cache
+        uses: actions/cache@v4
+        id: maven_local_repo_cache
         with:
-          path: "**/node_modules **/next/cache"
-          key: ${{ runner.os }}-node_modules_cache-${{ hashFiles('**/package-lock.json') }}
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
-            ${{ runner.os }}-node_modules_cache-
-
-      - name: Configure Github - AWS OICD
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::755840619199:role/github-to-aws-oicd
-          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-2
+            ${{ runner.os }}-maven-
 
       # B- build artifact
       - name: build artifact
-        run: mvn clean package  -DactiveProfile=dev
+        run: mvn clean package
 
       # C- Generate and publish test report for java artifact
       - name: Publish java test Results
@@ -65,7 +54,7 @@ jobs:
         id: jacoco_reporter
         uses: PavanMudigonda/jacoco-reporter@v4.8
         with:
-          coverage_results_path: ./arthur-digiboard-backend/target/site/jacoco/jacoco.xml
+          coverage_results_path: ./target/site/jacoco/jacoco.xml
           coverage_report_name: Coverage
           coverage_report_title: JaCoCo
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -99,65 +88,65 @@ jobs:
           name: Spotbugs
           path: build/reports/spotbugs/*.xml
 
-      # C- build and scan docker image
-      - name: Build and tag docker temp
-        run: |
-          docker build -t ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}} .
+      # # C- build and scan docker image
+      # - name: Build and tag docker temp
+      #   run: |
+      #     docker build -t ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}} .
 
       ## scan docker image for vulnerabilities
-      - name: Run Snyk to check Docker image for vulnerabilities
-        id: snyk_scan
-        continue-on-error: true
-        uses: snyk/actions/docker@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          image: ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}}
-          args: --file=Dockerfile --severity-threshold=high
+      # - name: Run Snyk to check Docker image for vulnerabilities
+      #   id: snyk_scan
+      #   continue-on-error: true
+      #   uses: snyk/actions/docker@master
+      #   env:
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #   with:
+      #     image: ${{env.REPOSITORY_NAME}}-temp:${{env.IMAGE_TAG}}
+      #     args: --file=Dockerfile --severity-threshold=high
 
-      - name: Upload result to GitHub Code Scanning
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: snyk.sarif
+      # - name: Upload result to GitHub Code Scanning
+      #   uses: github/codeql-action/upload-sarif@v2
+      #   with:
+      #     sarif_file: snyk.sarif
 
-      - name: Snyk Scan Result Check
-        if: ${{ steps.snyk_scan.outcome == 'failure' }}
-        run: |
-          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
-          exit 1
+      # - name: Snyk Scan Result Check
+      #   if: ${{ steps.snyk_scan.outcome == 'failure' }}
+      #   run: |
+      #     echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+      #     exit 1
 
-      - name: Login to Amazon ECR service
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-        with:
-          mask-password: "true"
+      # - name: Login to Amazon ECR service
+      #   id: login-ecr
+      #   uses: aws-actions/amazon-ecr-login@v2
+      #   with:
+      #     mask-password: "true"
 
-      - name: Push docker image to Amazon ECR
-        env:
-          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        run: |
-          docker tag ${{env.REPOSITORY_NAME}}-temp:${{ env.IMAGE_TAG}} $REGISTRY/${{env.REPOSITORY_NAME}}:${{env.IMAGE_TAG}}
-          docker push $REGISTRY/${{env.REPOSITORY_NAME}}:${{env.IMAGE_TAG}}
+      # - name: Push docker image to Amazon ECR
+      #   env:
+      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #   run: |
+      #     docker tag ${{env.REPOSITORY_NAME}}-temp:${{ env.IMAGE_TAG}} $REGISTRY/${{env.REPOSITORY_NAME}}:${{env.IMAGE_TAG}}
+      #     docker push $REGISTRY/${{env.REPOSITORY_NAME}}:${{env.IMAGE_TAG}}
 
-      - name: Install kubectl
-        uses: Azure/setup-kubectl@v3.2
-        # with:
-        #   version: "v1.27.0"
-        id: install
+      # - name: Install kubectl
+      #   uses: Azure/setup-kubectl@v3.2
+      #   # with:
+      #   #   version: "v1.27.0"
+      #   id: install
 
-      - name: Update kube config to set name & region & role
-        run: aws eks update-kubeconfig --name tf-cluster --region us-east-2
+      # - name: Update kube config to set name & region & role
+      #   run: aws eks update-kubeconfig --name tf-cluster --region us-east-2
 
-      - name: update helm dependencies
-        run: |
-          cd ./helm-charts/ 
-          helm dependency build
-          cd ..
-          echo "helm dependencies completed"
+      # - name: update helm dependencies
+      #   run: |
+      #     cd ./helm-charts/
+      #     helm dependency build
+      #     cd ..
+      #     echo "helm dependencies completed"
 
-      - name: Deploy application using helm
-        run: |
-          helm upgrade --install --wait --timeout 10m0s digiboard-application-chart ./helm-charts/
+      # - name: Deploy application using helm
+      #   run: |
+      #     helm upgrade --install --wait --timeout 10m0s digiboard-application-chart ./helm-charts/
 
       # - name: Deploy postgress db
       #   run: |
